Fix for custom fields containing multiple lines
CZ-NIC/python-rt pull request #61
Opened 2021-01-03 15:35 UTC by jerash

Fix for issue https://github.com/CZ-NIC/python-rt/issues/11
I use that in production for 3 months and no problem so far, hope it can be usefull

2021-01-04 13:27 UTC, e3rd commented
Cool, could you put a line in CHANGES under `v2.1.0, CURRENT_DATE`?

2021-01-06 22:51 UTC, jerash commented
i'm sorry idon't understand how to do what you ask

2021-01-07 12:14 UTC, e3rd commented
Don't mind, I'll do that. I plan to release a new minor version with this and #60 when ready.

2021-02-17 20:14 UTC, e3rd requested changes
The PR you've submitted concerns an important task. Would you be able to add a test case into `test_rt.py` for it please?

2021-02-17 20:14 UTC, e3rd commented on rt/rt.py
> +                elif msg[i] == "Cc:" or msg[i] == "AdminCc:":
When does `msg[i] == "Cc:"` happen? It seems to me the line 571 picks every `msg` that has a colon. Is it true that "Cc:" cannot be multiline?

2021-02-17 20:14 UTC, e3rd commented on rt/rt.py
> +                    # print("CANNOT PAIR with -" + msg[i] + "- using last header " + lastheader)
Join else-if to elif and get rid of "print" (or reformulate it to be a comment), not a leftover.

2021-04-08 11:01 UTC, e3rd commented
As this PR is stalled, it was superseded by #64

2021-04-08 11:01 UTC, closed without merging